name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Monorepo dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

  typechecks:
    needs: setup
    runs-on: ubuntu-latest
    working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{ needs.setup.outputs.new_sha }}'

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Run typecheck
        run: npm run tsc

  lint:
    needs: setup
    runs-on: ubuntu-latest
    working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{ needs.setup.outputs.new_sha }}'

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Run lint
        run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{ needs.setup.outputs.new_sha }}'

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        run: 'npm run test:ci'

      - name: Tests ✅
        if: '${{ success() }}'
        run: >
          curl --request POST \

          --url https://api.github.com/repos/${{ github.repository
          }}/statuses/${{ github.sha }} \

          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \

          --header 'content-type: application/json' \

          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: "Tests \U0001F6A8"
        if: '${{ failure() }}'
        run: >
          curl --request POST \

          --url https://api.github.com/repos/${{ github.repository
          }}/statuses/${{ github.sha }} \

          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \

          --header 'content-type: application/json' \

          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
